name-template: 'Release $RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
pull-request-limit: 15
exclude-labels:
  - 'skip-release'
  - 'no-release'
categories:
  - title: Breaking Changes 🛠
    labels:
      - major-change
      - breaking-change
  - title: Exciting New Features 🎉
    labels:
      - feature
      - enhancement
      - new-feature
  - title: Bug fixes 🐛
    labels:
      - bug
      - fix
      - hotfix
  - title: Infrastructure and DevOps 🚀
    labels:
      - infrastructure
      - devops
  - title: Documentation 📚
    labels:
      - documentation
      - docs
      - readme
  - title: UI Improvement 💅
    labels:
      - ui-improvement
      - ux-improvement
      - design
      - accessibility
  - title: Performance Improvements ⚡
    labels:
      - performance
      - optimization
  - title: Refactoring 🔨
    labels:
      - refactoring
  - title: Miscellaneous 🧩
    labels:
      - '*'
change-template: '- $TITLE #$NUMBER (@$AUTHOR)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'release:major'
      - 'major'
  minor:
    labels:
      - 'release:minor'
      - 'minor'
  patch:
    labels:
      - 'release:patch'
      - 'patch'
  default: patch
template: |
  ## $RESOLVED_VERSION
  put in release summary
  ### Highlights
  ## Detail
  ## Uncategorized
  $CHANGES
